let products = [
    {
        "id": 1001,
        "title": "Mathematics",
        "description": " A fun and interactive math lesson",
        "location": "5 James lane, N2",
        "price": 45,
        "image": "math1.png",
        "availableInventory":10,
        "rating": 3,
    },
    {
        "id": 1002,
        "title": "English",
        "description": " A fun and interactive english lesson",
        "location": "31 Amos lane, N4",
        "price": 30,
        "image": "math1.png",
        "availableInventory":15,
        "rating": 4,
    },
    {
        "id": 1003,
        "title": "Biology",
        "description": " A fun and interactive biology lesson",
        "location": "5 james lane, N2",
        "price": 35,
        "image": "math1.png",
        "availableInventory":20,
        "rating": 5,
    },
    {
        "id": 1004,
        "title": "Chemistry",
        "description": " A fun and interactive chemistry lesson",
        "location": "29 viking road, N3",
        "price": 35,
        "image": "math1.png",
        "availableInventory":20,
        "rating": 5,
    },
    {
        "id": 1005,
        "title": "Physics",
        "description": " A fun and interactive physics lesson",
        "location": "106 blackburn alley, N2",
        "price": 35,
        "image": "math1.png",
        "availableInventory":20,
        "rating": 4,
    },

]